version: "2.1"

services:
    sql_server:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1434:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrongPassword12!@
        volumes:
            - sqldata:/var/opt/mssql
        networks:
            - booksrentalsystem-network

    eventstore:
        container_name: eventstore
        image: eventstore/eventstore:21.2.0-buster-slim
        ports:
            - "2115:2113"
            - "1115:1113"
        volumes:
            - type: volume
              source: eventstore-data
              target: /var/lib/eventstore
        environment:
            EVENTSTORE_EXT_HTTP_PORT: 2113
            EVENTSTORE_EXT_TCP_PORT: 1113
            EVENTSTORE_RUN_PROJECTIONS: all
            EVENTSTORE_START_STANDARD_PROJECTIONS: 'true'
            PROJECTION_THREADS: 8
            EVENTSTORE_INSECURE: 'true'
            EVENTSTORE_ENABLE_EXTERNAL_TCP: 'true'
            EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: 'true'
        networks:
            - booksrentalsystem-network

    mongo:
        image: mongo:4.4.1
        ports:
            - "27018:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - booksrentalsystem-network

    minio:
        image: minio/minio:latest
        ports:
            - "9000:9000"
            - "9002:9002"
        environment:
            MINIO_ROOT_USER: root
            MINIO_ROOT_PASSWORD: minioStrongPassword12!@
        volumes:
            - minio-data:/data
        command: server /data --console-address ":9002"
        networks:
            - booksrentalsystem-network

    identity:
        container_name: identity
        image: volodymyr04/booksrentalsystem-identity-service:1.0
        build:
            context: ./
            dockerfile: ./BooksRentalSystem.Identity/Dockerfile
        ports:
            - "5001:80"
        env_file: BooksRentalSystem.Common/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BooksRentalIdentityDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true;TrustServerCertificate=True;
            - ConnectionStrings__EventStore=esdb://eventstore?tls=false
            - IdentitySettings__AdminPassword=adminpass12!
        restart: on-failure
        # volumes:
        #     - ./.aspnet/identity/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks:
            - booksrentalsystem-network
        depends_on:
            - sql_server
            - eventstore

    publishers:
        container_name: publishers
        image: volodymyr04/booksrentalsystem-publishers-service:1.0
        build:
            context: ./
            dockerfile: ./BooksRentalSystem.Publishers/Dockerfile
        ports:
            - "5002:80"
        env_file:
            - BooksRentalSystem.Common/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BooksRentalPublishersDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true;TrustServerCertificate=True;
            - ConnectionStrings__EventStore=esdb://eventstore?tls=false
            - ConnectionStrings__CronJobsConnection=Server=sqlserver;Database=BooksRentalPublishersCronJobsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true;TrustServerCertificate=True;
        restart: on-failure
        # volumes:
        #     - ./.aspnet/publishers/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks:
            - booksrentalsystem-network
        depends_on:
            - sql_server
            - eventstore

    publishers_projections:
        container_name: publishers-projections
        image: volodymyr04/booksrentalsystem-publishers-projections:1.0
        build:
            context: ./
            dockerfile: ./BooksRentalSystem.Publishers.Projections/Dockerfile
        ports:
            - "5012:80"
        env_file:
            - BooksRentalSystem.Common/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BooksRentalPublishersDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true;TrustServerCertificate=True;
            - ConnectionStrings__EventStore=esdb://eventstore?tls=false
        restart: on-failure
        # volumes:
        #     - ./.aspnet/publishers/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks:
            - booksrentalsystem-network
        depends_on:
            - sql_server
            - eventstore

    statistics:
        container_name: statistics
        image: volodymyr04/booksrentalsystem-statistics-service:1.0
        build:
            context: ./
            dockerfile: ./BooksRentalSystem.Statistics/Dockerfile
        ports:
            - "5003:80"
        env_file:
            - BooksRentalSystem.Common/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BooksRentalStatisticsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true;TrustServerCertificate=True;
            - ConnectionStrings__CronJobsConnection=Server=sqlserver;Database=BooksRentalStatisticsCronJobsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true;TrustServerCertificate=True;
            - ConnectionStrings__EventStore=esdb://eventstore?tls=false
        restart: on-failure
        # volumes:
        #     - ./.aspnet/statistics/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks:
            - booksrentalsystem-network
        depends_on:
            - sql_server
            - eventstore

    notifications:
        container_name: notifications
        image: volodymyr04/booksrentalsystem-notifications-service:1.0
        build:
            context: ./
            dockerfile: ./BooksRentalSystem.Notifications/Dockerfile
        ports:
            - "5004:80"
        env_file:
            - BooksRentalSystem.Common/Common.env
        environment:
            - ConnectionStrings__EventStore=esdb://eventstore?tls=false
            - NotificationSettings__AllowedOrigins=http://localhost
        restart: on-failure
        # volumes:
        #     - ./.aspnet/notifications/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks:
            - booksrentalsystem-network
        depends_on:
            - eventstore

    admin:
        container_name: admin
        image: volodymyr04/booksrentalsystem-admin-client:1.0
        build:
            context: ./
            dockerfile: ./BooksRentalSystem.Admin/Dockerfile
        ports:
            - "5000:80"
        env_file: BooksRentalSystem.Common/Common.env
        environment:
            - ServiceEndpoints__Identity=http://identity
            - ServiceEndpoints__Publishers=http://publishers
            - ServiceEndpoints__Statistics=http://statistics
        restart: on-failure
        # volumes:
        #     - ./.aspnet/admin/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks:
            - booksrentalsystem-network
        depends_on:
            - identity
            - publishers
            - statistics

    client:
        container_name: client
        image: volodymyr04/booksrentalsystem-user-client:1.0
        build:
            context: ./BooksRentalSystem.WebApp
            dockerfile: ./Dockerfile
        #            args:
        #                configuration: development
        ports:
            - "80:80"
        restart: on-failure
        depends_on:
            - identity
            - publishers
            - statistics
            - notifications

    watchdog:
        container_name: watchdog
        image: volodymyr04/booksrentalsystem-watchdog-service:1.0
        build:
            context: ./
            dockerfile: ./BooksRentalSystem.Watchdog/Dockerfile
        ports:
            - "5500:80"
        environment:
            - HealthChecks-UI__HealthChecks__0__Name=Identity
            - HealthChecks-UI__HealthChecks__0__Uri=http://identity/health
            - HealthChecks-UI__HealthChecks__1__Name=Publishers
            - HealthChecks-UI__HealthChecks__1__Uri=http://publishers/health
            - HealthChecks-UI__HealthChecks__2__Name=Statistics
            - HealthChecks-UI__HealthChecks__2__Uri=http://statistics/health
            - HealthChecks-UI__HealthChecks__3__Name=Notifications
            - HealthChecks-UI__HealthChecks__3__Uri=http://notifications/health
            - HealthChecks-UI__HealthChecks__4__Name=Admin
            - HealthChecks-UI__HealthChecks__4__Uri=http://admin/health
        restart: on-failure
        networks:
            - booksrentalsystem-network
        depends_on:
            - identity
            - publishers
            - statistics
            - notifications
            - admin

networks:
    booksrentalsystem-network:

volumes:
    sqldata:
    eventstore-data:
    mongo-data:
    minio-data:
